// export const ACTION_NAME = "MODULE1/EVENT/ACTION_NAME";

export const SET_USER_NAME = "MODULE1/EVENT/SET_USER_NAME";
export const SET_USER_FLAG = "MODULE1/EVENT/SET_USER_FLAG";

export const UPDATE_USER_INFO = "MODULE1/EVENT/SET_USER_DETAILS";
export const RUN_APP_START = "MODULE1/EVENT/RUN_APP_START";
